# Generated by Django 6.0.3 on 2026-04-05 20:30

import django.db.models.deletion
import lexnote.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('mail_enabled', models.BooleanField(default=False)),
                ('security_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('html_content', models.TextField(help_text='Use placeholders like {{display_name}}, {{designation}}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(help_text='M365 Directory ID', max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('relay_domain', models.CharField(help_text='e.g. x1y2.smtp.lexnote.org', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LexUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('upn', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(related_name='members', to='lexnote.group')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='lexnote.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('target_groups', models.ManyToManyField(blank=True, to='lexnote.group')),
                ('target_users', models.ManyToManyField(blank=True, to='lexnote.lexuser')),
                ('initial_signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_policy', to='lexnote.signaturetemplate')),
                ('reply_signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_policy', to='lexnote.signaturetemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnote.tenant')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='lexnote.tenant'),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trn', models.CharField(db_index=True, default=lexnote.models.generate_trn, max_length=50, unique=True)),
                ('trigger_type', models.CharField(choices=[('MAIL', 'Mail Traffic'), ('SYNC', 'Directory Sync')], default='MAIL', max_length=10)),
                ('sender', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('internet_message_id', models.CharField(blank=True, db_index=True, max_length=998)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('signed', 'Signed'), ('bypassed', 'Bypassed'), ('failed', 'Failed'), ('returned', 'Returned'), ('sync_success', 'Sync Success'), ('sync_fail', 'Sync Failed')], db_index=True, default='received', max_length=20)),
                ('is_reply', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('directory_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexnote.lexuser')),
                ('policy_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexnote.policy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lexnote.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lexnote.transactionlog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='lexnote_tra_tenant__6cf54f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['trn', 'sender'], name='lexnote_tra_trn_c7fd54_idx'),
        ),
    ]
