# Generated by Django 6.0.3 on 2026-04-04 09:57

import django.db.models.deletion
import lexnote.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('html_content', models.TextField()),
                ('sig_type', models.CharField(choices=[('initial', 'Initial Email'), ('reply', 'Reply/Forward'), ('universal', 'Universal (Both)')], default='universal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('relay_token', models.CharField(default=lexnote.models.generate_relay_token, max_length=20, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='lexnote.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SignaturePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('target_department', models.CharField(blank=True, max_length=100)),
                ('target_company', models.CharField(blank=True, max_length=255)),
                ('initial_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_sig', to='lexnote.signaturetemplate')),
                ('reply_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_sig', to='lexnote.signaturetemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnote.tenant')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexnote.tenantdomain')),
            ],
            options={
                'verbose_name_plural': 'Signature Policies',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnote.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'tenant'], name='lexnote_dir_email_9a26de_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trn', models.CharField(default=lexnote.models.generate_trn, editable=False, max_length=50, unique=True)),
                ('message_id', models.CharField(db_index=True, help_text='Original Message-ID header', max_length=255)),
                ('sender', models.EmailField(db_index=True, max_length=254)),
                ('recipient', models.TextField(help_text='Comma-separated list of recipients')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('signed', 'Signed'), ('bypassed', 'Bypassed'), ('failed', 'Failed')], max_length=20)),
                ('is_reply', models.BooleanField(default=False, help_text='Detected via In-Reply-To header')),
                ('cross_tenant_id', models.UUIDField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('policy_applied', models.ForeignKey(blank=True, help_text='The specific policy that matched the sender attributes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lexnote.signaturepolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnote.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trn', 'sender'], name='lexnote_tra_trn_c7fd54_idx'), models.Index(fields=['timestamp', 'status'], name='lexnote_tra_timesta_ec79ed_idx')],
            },
        ),
    ]
