# Generated by Django 6.0.3 on 2026-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='lexuser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
