# Generated by Django 6.0.3 on 2026-04-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnote', '0002_group_is_active_lexuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexuser',
            name='office_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
