# Generated by Django 6.0.3 on 2026-04-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnote', '0003_lexuser_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='exclude_departments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='exclude_groups',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_policies', to='lexnote.group'),
        ),
        migrations.AddField(
            model_name='policy',
            name='exclude_users',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_policies', to='lexnote.lexuser'),
        ),
        migrations.AddField(
            model_name='policy',
            name='target_cities',
            field=models.TextField(blank=True, help_text='Comma-separated list of cities.'),
        ),
        migrations.AddField(
            model_name='policy',
            name='target_companies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='target_departments',
            field=models.TextField(blank=True, help_text='Comma-separated list of departments.'),
        ),
        migrations.AddField(
            model_name='policy',
            name='target_office_locations',
            field=models.TextField(blank=True, help_text="Matches against the 'city' or 'office_location' field."),
        ),
        migrations.AddField(
            model_name='policy',
            name='target_states',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority policies are evaluated first.'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='targeted_by_policies', to='lexnote.group'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_by_policies', to='lexnote.lexuser'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'is_active', 'priority'], name='lexnote_pol_tenant__f3d9e4_idx'),
        ),
    ]
