# Generated by Django 6.0.3 on 2026-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnote', '0004_policy_exclude_departments_policy_exclude_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='cross_tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='recipients',
            field=models.JSONField(default=dict),
        ),
    ]
